name: Game Updater

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  updater:
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'tspivey'
    runs-on: ubuntu-latest
    steps:
    - name: SSH into server and run commands
      uses: appleboy/ssh-action@master
      with:
        host: allinaccess.com
        username: yugioh
        password: ${{ secrets.SSH_KEY }}
        script: |
          ./update.sh
